// Comprehensive English verbs with all 4 forms (V1, V2, V3, -ing) + example
window.VERB_DATA = [
  // === Be / auxiliary ===
  ['be','was/were','been','being','I am a student. He was happy. She has been here.'],
  ['have','had','had','having','I have a question.'],
  ['do','did','done','doing','I do my homework daily.'],

  // === Irregular verbs ===
  ['arise','arose','arisen','arising','A new problem arose.'],
  ['awake','awoke','awoken','awaking','I awake at six.'],
  ['bear','bore','borne','bearing','She bore the pain bravely.'],
  ['beat','beat','beaten','beating','We beat them in the match.'],
  ['become','became','become','becoming','He became a teacher.'],
  ['begin','began','begun','beginning','The class begins at 9.'],
  ['bend','bent','bent','bending','Bend your knees slowly.'],
  ['bet','bet','bet','betting','I bet you cannot do it.'],
  ['bid','bid','bid','bidding','He bid a high price.'],
  ['bind','bound','bound','binding','Bind the books together.'],
  ['bite','bit','bitten','biting','The dog bit him.'],
  ['bleed','bled','bled','bleeding','My finger is bleeding.'],
  ['blow','blew','blown','blowing','The wind blew strongly.'],
  ['break','broke','broken','breaking','Do not break the rules.'],
  ['breed','bred','bred','breeding','They breed dogs.'],
  ['bring','brought','brought','bringing','Please bring your book.'],
  ['build','built','built','building','They built a new classroom.'],
  ['burn','burnt','burnt','burning','The candle is burning.'],
  ['burst','burst','burst','bursting','The balloon burst.'],
  ['buy','bought','bought','buying','I bought a dictionary.'],
  ['cast','cast','cast','casting','Cast your vote.'],
  ['catch','caught','caught','catching','Catch the ball.'],
  ['choose','chose','chosen','choosing','Choose any topic.'],
  ['cling','clung','clung','clinging','The child clung to her mother.'],
  ['come','came','come','coming','Come here, please.'],
  ['cost','cost','cost','costing','The book costs ₹100.'],
  ['creep','crept','crept','creeping','The cat crept silently.'],
  ['cut','cut','cut','cutting','Cut the paper carefully.'],
  ['deal','dealt','dealt','dealing','He deals with customers.'],
  ['dig','dug','dug','digging','They dug a deep hole.'],
  ['draw','drew','drawn','drawing','She draws very well.'],
  ['dream','dreamt','dreamt','dreaming','I dreamt of flying.'],
  ['drink','drank','drunk','drinking','Drink water often.'],
  ['drive','drove','driven','driving','He drives to college.'],
  ['eat','ate','eaten','eating','We eat lunch at one.'],
  ['fall','fell','fallen','falling','Be careful, do not fall.'],
  ['feed','fed','fed','feeding','I feed my dog daily.'],
  ['feel','felt','felt','feeling','I feel happy today.'],
  ['fight','fought','fought','fighting','Do not fight with anyone.'],
  ['find','found','found','finding','I found my book.'],
  ['flee','fled','fled','fleeing','They fled the city.'],
  ['fling','flung','flung','flinging','He flung the ball.'],
  ['fly','flew','flown','flying','Birds fly in the sky.'],
  ['forbid','forbade','forbidden','forbidding','He forbade me to go.'],
  ['forecast','forecast','forecast','forecasting','They forecast rain.'],
  ['forget','forgot','forgotten','forgetting','Do not forget your bag.'],
  ['forgive','forgave','forgiven','forgiving','Please forgive me.'],
  ['forsake','forsook','forsaken','forsaking','Do not forsake your friends.'],
  ['freeze','froze','frozen','freezing','The pond froze.'],
  ['get','got','got/gotten','getting','I get up at six.'],
  ['give','gave','given','giving','Give me a chance.'],
  ['go','went','gone','going','He goes to school.'],
  ['grind','ground','ground','grinding','She ground the spices.'],
  ['grow','grew','grown','growing','Plants grow with sunlight.'],
  ['hang','hung','hung','hanging','The picture hangs on the wall.'],
  ['hear','heard','heard','hearing','Did you hear the news?'],
  ['hide','hid','hidden','hiding','He hid the gift.'],
  ['hit','hit','hit','hitting','Do not hit anyone.'],
  ['hold','held','held','holding','Hold this book for me.'],
  ['hurt','hurt','hurt','hurting','My head hurts.'],
  ['keep','kept','kept','keeping','Keep your room clean.'],
  ['kneel','knelt','knelt','kneeling','He knelt on the floor.'],
  ['know','knew','known','knowing','I know the answer.'],
  ['lay','laid','laid','laying','Lay the book on the table.'],
  ['lead','led','led','leading','She leads the discussion.'],
  ['lean','leant','leant','leaning','He leant against the wall.'],
  ['leap','leapt','leapt','leaping','The frog leapt away.'],
  ['learn','learnt/learned','learnt/learned','learning','We learn English here.'],
  ['leave','left','left','leaving','Leave your bag here.'],
  ['lend','lent','lent','lending','Can you lend me a pen?'],
  ['let','let','let','letting','Let me try.'],
  ['lie','lay','lain','lying','Do not lie to your teacher.'],
  ['light','lit','lit','lighting','He lit the lamp.'],
  ['lose','lost','lost','losing','Do not lose your books.'],
  ['make','made','made','making','I am making notes.'],
  ['mean','meant','meant','meaning','What does this word mean?'],
  ['meet','met','met','meeting','I met her yesterday.'],
  ['mistake','mistook','mistaken','mistaking','I mistook him for his brother.'],
  ['overcome','overcame','overcome','overcoming','He overcame his fear.'],
  ['pay','paid','paid','paying','He paid the fees.'],
  ['put','put','put','putting','Put your books here.'],
  ['quit','quit','quit','quitting','He quit smoking.'],
  ['read','read','read','reading','I read every day.'],
  ['ride','rode','ridden','riding','He rides a bicycle.'],
  ['ring','rang','rung','ringing','The bell rang.'],
  ['rise','rose','risen','rising','The sun rises in the east.'],
  ['run','ran','run','running','I run every morning.'],
  ['saw','sawed','sawn','sawing','He sawed the wood.'],
  ['say','said','said','saying','Say it again, please.'],
  ['see','saw','seen','seeing','I see you.'],
  ['seek','sought','sought','seeking','They are seeking help.'],
  ['sell','sold','sold','selling','They sell books here.'],
  ['send','sent','sent','sending','Send me a message.'],
  ['set','set','set','setting','Set the chairs in a row.'],
  ['sew','sewed','sewn','sewing','She sewed the dress.'],
  ['shake','shook','shaken','shaking','Shake hands politely.'],
  ['shine','shone','shone','shining','The sun is shining.'],
  ['shoot','shot','shot','shooting','He shot the ball.'],
  ['show','showed','shown','showing','Show me your homework.'],
  ['shrink','shrank','shrunk','shrinking','The shirt shrank.'],
  ['shut','shut','shut','shutting','Shut the door, please.'],
  ['sing','sang','sung','singing','She sings beautifully.'],
  ['sink','sank','sunk','sinking','The boat sank.'],
  ['sit','sat','sat','sitting','Please sit down.'],
  ['sleep','slept','slept','sleeping','I slept well last night.'],
  ['slide','slid','slid','sliding','He slid down the slope.'],
  ['speak','spoke','spoken','speaking','Speak in English.'],
  ['speed','sped','sped','speeding','The car sped past.'],
  ['spell','spelt','spelt','spelling','How do you spell that?'],
  ['spend','spent','spent','spending','He spent the day reading.'],
  ['spill','spilt','spilt','spilling','Do not spill the milk.'],
  ['spin','spun','spun','spinning','The earth spins on its axis.'],
  ['split','split','split','splitting','Let us split the bill.'],
  ['spread','spread','spread','spreading','News spreads fast.'],
  ['spring','sprang','sprung','springing','He sprang to action.'],
  ['stand','stood','stood','standing','Stand up, please.'],
  ['steal','stole','stolen','stealing','Do not steal anything.'],
  ['stick','stuck','stuck','sticking','Stick to your plan.'],
  ['sting','stung','stung','stinging','A bee stung me.'],
  ['stink','stank','stunk','stinking','The drain stinks.'],
  ['strike','struck','struck','striking','Strike while the iron is hot.'],
  ['swear','swore','sworn','swearing','I swear to tell the truth.'],
  ['sweep','swept','swept','sweeping','Sweep the floor.'],
  ['swim','swam','swum','swimming','I can swim.'],
  ['swing','swung','swung','swinging','He swung the bat.'],
  ['take','took','taken','taking','Take your seat.'],
  ['teach','taught','taught','teaching','She teaches English.'],
  ['tear','tore','torn','tearing','He tore the paper.'],
  ['tell','told','told','telling','Tell the truth.'],
  ['think','thought','thought','thinking','I think you are right.'],
  ['throw','threw','thrown','throwing','Throw the ball.'],
  ['thrust','thrust','thrust','thrusting','He thrust the door open.'],
  ['tread','trod','trodden','treading','Do not tread on the grass.'],
  ['undergo','underwent','undergone','undergoing','She underwent surgery.'],
  ['understand','understood','understood','understanding','I understand the lesson.'],
  ['undertake','undertook','undertaken','undertaking','He undertook the project.'],
  ['upset','upset','upset','upsetting','The news upset her.'],
  ['wake','woke','woken','waking','I wake up at six.'],
  ['wear','wore','worn','wearing','Wear your uniform.'],
  ['weave','wove','woven','weaving','She weaves carpets.'],
  ['weep','wept','wept','weeping','The child wept.'],
  ['win','won','won','winning','He won the competition.'],
  ['wind','wound','wound','winding','He wound the rope.'],
  ['withdraw','withdrew','withdrawn','withdrawing','I withdrew money from the bank.'],
  ['wring','wrung','wrung','wringing','She wrung out the wet cloth.'],
  ['write','wrote','written','writing','Write a paragraph.'],

  // === Regular verbs ===
  ['accept','accepted','accepted','accepting','I accept your apology.'],
  ['add','added','added','adding','Add some sugar.'],
  ['admit','admitted','admitted','admitting','He admitted his mistake.'],
  ['agree','agreed','agreed','agreeing','I agree with you.'],
  ['allow','allowed','allowed','allowing','We are not allowed to talk.'],
  ['answer','answered','answered','answering','Answer in full sentences.'],
  ['appear','appeared','appeared','appearing','He appeared confident.'],
  ['arrive','arrived','arrived','arriving','We arrived early.'],
  ['ask','asked','asked','asking','Ask any question.'],
  ['attend','attended','attended','attending','I attend class daily.'],
  ['behave','behaved','behaved','behaving','Behave well in class.'],
  ['believe','believed','believed','believing','I believe in you.'],
  ['belong','belonged','belonged','belonging','This belongs to me.'],
  ['borrow','borrowed','borrowed','borrowing','May I borrow your pen?'],
  ['call','called','called','calling','Call me later.'],
  ['carry','carried','carried','carrying','She carried the bag.'],
  ['change','changed','changed','changing','Change your habits.'],
  ['check','checked','checked','checking','Check your answers.'],
  ['close','closed','closed','closing','Close the window.'],
  ['compare','compared','compared','comparing','Compare both options.'],
  ['complete','completed','completed','completing','I completed the work.'],
  ['cook','cooked','cooked','cooking','My mother cooks well.'],
  ['copy','copied','copied','copying','Do not copy from others.'],
  ['count','counted','counted','counting','Count the chairs.'],
  ['cross','crossed','crossed','crossing','Cross the road carefully.'],
  ['cry','cried','cried','crying','Why is the baby crying?'],
  ['dance','danced','danced','dancing','We dance at every event.'],
  ['decide','decided','decided','deciding','I decided to join.'],
  ['describe','described','described','describing','Describe yourself.'],
  ['die','died','died','dying','The plant is dying.'],
  ['discuss','discussed','discussed','discussing','We discussed the topic.'],
  ['dress','dressed','dressed','dressing','He dressed quickly.'],
  ['enjoy','enjoyed','enjoyed','enjoying','I enjoy the class.'],
  ['enter','entered','entered','entering','Please enter the room.'],
  ['exercise','exercised','exercised','exercising','I exercise every morning.'],
  ['expect','expected','expected','expecting','We expect rain.'],
  ['explain','explained','explained','explaining','Please explain again.'],
  ['fail','failed','failed','failing','He failed the test.'],
  ['fill','filled','filled','filling','Fill the form.'],
  ['finish','finished','finished','finishing','Finish your work first.'],
  ['fix','fixed','fixed','fixing','Can you fix this?'],
  ['follow','followed','followed','following','Follow the rules.'],
  ['greet','greeted','greeted','greeting','He greeted us warmly.'],
  ['guess','guessed','guessed','guessing','Guess my age.'],
  ['hate','hated','hated','hating','I hate liars.'],
  ['help','helped','helped','helping','I will help you.'],
  ['hope','hoped','hoped','hoping','I hope you succeed.'],
  ['hurry','hurried','hurried','hurrying','Hurry up, we are late.'],
  ['imagine','imagined','imagined','imagining','Imagine being there.'],
  ['improve','improved','improved','improving','My English is improving.'],
  ['invite','invited','invited','inviting','I invited my friends.'],
  ['join','joined','joined','joining','Join the discussion.'],
  ['jump','jumped','jumped','jumping','Do not jump on the bed.'],
  ['kick','kicked','kicked','kicking','He kicked the ball.'],
  ['kiss','kissed','kissed','kissing','She kissed her child.'],
  ['laugh','laughed','laughed','laughing','We laughed at the joke.'],
  ['like','liked','liked','liking','I like English class.'],
  ['listen','listened','listened','listening','Listen carefully.'],
  ['live','lived','lived','living','We live in Sidhi.'],
  ['look','looked','looked','looking','Look at the board.'],
  ['love','loved','loved','loving','I love learning English.'],
  ['mark','marked','marked','marking','Mark the correct answer.'],
  ['marry','married','married','marrying','They married last year.'],
  ['miss','missed','missed','missing','I missed the bus.'],
  ['mix','mixed','mixed','mixing','Mix the ingredients.'],
  ['move','moved','moved','moving','We moved to a new house.'],
  ['need','needed','needed','needing','I need your help.'],
  ['notice','noticed','noticed','noticing','I noticed the change.'],
  ['offer','offered','offered','offering','He offered me tea.'],
  ['open','opened','opened','opening','Open your book.'],
  ['order','ordered','ordered','ordering','I ordered food online.'],
  ['paint','painted','painted','painting','She painted the wall.'],
  ['pass','passed','passed','passing','He passed the exam.'],
  ['plan','planned','planned','planning','We are planning a trip.'],
  ['play','played','played','playing','Children play in the ground.'],
  ['practice','practiced','practiced','practicing','Practice every day.'],
  ['prefer','preferred','preferred','preferring','I prefer tea to coffee.'],
  ['prepare','prepared','prepared','preparing','Prepare for the test.'],
  ['promise','promised','promised','promising','He promised to come.'],
  ['pull','pulled','pulled','pulling','Pull the door.'],
  ['push','pushed','pushed','pushing','Push gently.'],
  ['receive','received','received','receiving','I received your message.'],
  ['refuse','refused','refused','refusing','He refused to help.'],
  ['relax','relaxed','relaxed','relaxing','I am relaxing today.'],
  ['remember','remembered','remembered','remembering','Remember your goal.'],
  ['repeat','repeated','repeated','repeating','Repeat after me.'],
  ['reply','replied','replied','replying','Please reply to my email.'],
  ['rest','rested','rested','resting','He rested for an hour.'],
  ['return','returned','returned','returning','Return the book on time.'],
  ['save','saved','saved','saving','Save your work.'],
  ['shop','shopped','shopped','shopping','We shop on Sundays.'],
  ['shout','shouted','shouted','shouting','Do not shout in class.'],
  ['smile','smiled','smiled','smiling','She smiled warmly.'],
  ['solve','solved','solved','solving','Solve this problem.'],
  ['stop','stopped','stopped','stopping','Stop talking, please.'],
  ['study','studied','studied','studying','I study English.'],
  ['talk','talked','talked','talking','We talk in English.'],
  ['thank','thanked','thanked','thanking','I thanked him politely.'],
  ['travel','travelled','travelled','travelling','We travelled by train.'],
  ['try','tried','tried','trying','Try your best.'],
  ['turn','turned','turned','turning','Turn off the light.'],
  ['use','used','used','using','Use this dictionary.'],
  ['visit','visited','visited','visiting','I visited my grandmother.'],
  ['wait','waited','waited','waiting','Wait for me here.'],
  ['walk','walked','walked','walking','Walk to the park.'],
  ['want','wanted','wanted','wanting','I want to learn.'],
  ['wash','washed','washed','washing','Wash your hands.'],
  ['watch','watched','watched','watching','Watch the video.'],
  ['work','worked','worked','working','I work in Sidhi.'],
  ['worry','worried','worried','worrying','Do not worry about it.']
];
