window.VERB_DATA = [
  ['be','was/were','been','being','I am a student. He was happy. She has been here.'],
  ['become','became','become','becoming','He became a teacher.'],
  ['begin','began','begun','beginning','The class begins at 9.'],
  ['break','broke','broken','breaking','Do not break the rules.'],
  ['bring','brought','brought','bringing','Please bring your book.'],
  ['build','built','built','building','They built a new classroom.'],
  ['buy','bought','bought','buying','I bought a dictionary.'],
  ['catch','caught','caught','catching','Catch the ball.'],
  ['choose','chose','chosen','choosing','Choose any topic.'],
  ['come','came','come','coming','Come here, please.'],
  ['cost','cost','cost','costing','The book costs ₹100.'],
  ['cut','cut','cut','cutting','Cut the paper carefully.'],
  ['do','did','done','doing','I do my homework daily.'],
  ['draw','drew','drawn','drawing','She draws very well.'],
  ['drink','drank','drunk','drinking','Drink water often.'],
  ['drive','drove','driven','driving','He drives to college.'],
  ['eat','ate','eaten','eating','We eat lunch at one.'],
  ['fall','fell','fallen','falling','Be careful, do not fall.'],
  ['feel','felt','felt','feeling','I feel happy today.'],
  ['fight','fought','fought','fighting','Do not fight with anyone.'],
  ['find','found','found','finding','I found my book.'],
  ['fly','flew','flown','flying','Birds fly in the sky.'],
  ['forget','forgot','forgotten','forgetting','Do not forget your bag.'],
  ['forgive','forgave','forgiven','forgiving','Please forgive me.'],
  ['get','got','got/gotten','getting','I get up at six.'],
  ['give','gave','given','giving','Give me a chance.'],
  ['go','went','gone','going','He goes to school.'],
  ['grow','grew','grown','growing','Plants grow with sunlight.'],
  ['have','had','had','having','I have a question.'],
  ['hear','heard','heard','hearing','Did you hear the news?'],
  ['hide','hid','hidden','hiding','He hid the gift.'],
  ['hit','hit','hit','hitting','Do not hit anyone.'],
  ['hold','held','held','holding','Hold this book for me.'],
  ['hurt','hurt','hurt','hurting','My head hurts.'],
  ['keep','kept','kept','keeping','Keep your room clean.'],
  ['know','knew','known','knowing','I know the answer.'],
  ['lay','laid','laid','laying','Lay the book on the table.'],
  ['lead','led','led','leading','She leads the discussion.'],
  ['learn','learnt/learned','learnt/learned','learning','We learn English here.'],
  ['leave','left','left','leaving','Leave your bag here.'],
  ['lend','lent','lent','lending','Can you lend me a pen?'],
  ['let','let','let','letting','Let me try.'],
  ['lie','lay','lain','lying','Do not lie to your teacher.'],
  ['lose','lost','lost','losing','Do not lose your books.'],
  ['make','made','made','making','I am making notes.'],
  ['mean','meant','meant','meaning','What does this word mean?'],
  ['meet','met','met','meeting','I met her yesterday.'],
  ['pay','paid','paid','paying','He paid the fees.'],
  ['put','put','put','putting','Put your books here.'],
  ['read','read','read','reading','I read every day.'],
  ['ride','rode','ridden','riding','He rides a bicycle.'],
  ['ring','rang','rung','ringing','The bell rang.'],
  ['rise','rose','risen','rising','The sun rises in the east.'],
  ['run','ran','run','running','I run every morning.'],
  ['say','said','said','saying','Say it again, please.'],
  ['see','saw','seen','seeing','I see you.'],
  ['sell','sold','sold','selling','They sell books here.'],
  ['send','sent','sent','sending','Send me a message.'],
  ['set','set','set','setting','Set the chairs in a row.'],
  ['shake','shook','shaken','shaking','Shake hands politely.'],
  ['shine','shone','shone','shining','The sun is shining.'],
  ['shoot','shot','shot','shooting','He shot the ball into the goal.'],
  ['show','showed','shown','showing','Show me your homework.'],
  ['shut','shut','shut','shutting','Shut the door, please.'],
  ['sing','sang','sung','singing','She sings beautifully.'],
  ['sit','sat','sat','sitting','Please sit down.'],
  ['sleep','slept','slept','sleeping','I slept well last night.'],
  ['speak','spoke','spoken','speaking','Speak in English.'],
  ['spend','spent','spent','spending','He spent the day reading.'],
  ['stand','stood','stood','standing','Stand up, please.'],
  ['steal','stole','stolen','stealing','Do not steal anything.'],
  ['stick','stuck','stuck','sticking','Stick to your plan.'],
  ['swim','swam','swum','swimming','I can swim.'],
  ['take','took','taken','taking','Take your seat.'],
  ['teach','taught','taught','teaching','She teaches English.'],
  ['tell','told','told','telling','Tell the truth.'],
  ['think','thought','thought','thinking','I think you are right.'],
  ['throw','threw','thrown','throwing','Throw the ball.'],
  ['understand','understood','understood','understanding','I understand the lesson.'],
  ['wake','woke','woken','waking','I wake up at six.'],
  ['wear','wore','worn','wearing','Wear your uniform.'],
  ['win','won','won','winning','He won the competition.'],
  ['write','wrote','written','writing','Write a paragraph.'],
  // Regular verbs
  ['ask','asked','asked','asking','Ask any question.'],
  ['answer','answered','answered','answering','Answer in full sentences.'],
  ['call','called','called','calling','Call me later.'],
  ['change','changed','changed','changing','Change your habits.'],
  ['close','closed','closed','closing','Close the window.'],
  ['cook','cooked','cooked','cooking','My mother cooks well.'],
  ['dance','danced','danced','dancing','We dance at every event.'],
  ['decide','decided','decided','deciding','I decided to join.'],
  ['discuss','discussed','discussed','discussing','We discussed the topic.'],
  ['enjoy','enjoyed','enjoyed','enjoying','I enjoy the class.'],
  ['explain','explained','explained','explaining','Please explain again.'],
  ['finish','finished','finished','finishing','Finish your work first.'],
  ['help','helped','helped','helping','I will help you.'],
  ['improve','improved','improved','improving','My English is improving.'],
  ['join','joined','joined','joining','Join the discussion.'],
  ['like','liked','liked','liking','I like English class.'],
  ['listen','listened','listened','listening','Listen carefully.'],
  ['live','lived','lived','living','We live in Sidhi.'],
  ['look','looked','looked','looking','Look at the board.'],
  ['love','loved','loved','loving','I love learning English.'],
  ['need','needed','needed','needing','I need your help.'],
  ['open','opened','opened','opening','Open your book.'],
  ['plan','planned','planned','planning','We are planning a trip.'],
  ['play','played','played','playing','Children play in the ground.'],
  ['practice','practiced','practiced','practicing','Practice every day.'],
  ['repeat','repeated','repeated','repeating','Repeat after me.'],
  ['stop','stopped','stopped','stopping','Stop talking, please.'],
  ['study','studied','studied','studying','I study English.'],
  ['talk','talked','talked','talking','We talk in English.'],
  ['try','tried','tried','trying','Try your best.'],
  ['use','used','used','using','Use this dictionary.'],
  ['walk','walked','walked','walking','Walk to the park.'],
  ['want','wanted','wanted','wanting','I want to learn.'],
  ['watch','watched','watched','watching','Watch the video.'],
  ['work','worked','worked','working','I work in Sidhi.']
];
